### ISSUE TITLE
Take only a folder of a release zip?

### ISSUE THREAD

**Issue by goaround** [inpsyde/composer-asset-compiler#5]
Hi,

first: thank you very much for this composer plugin! 

I have a suggestion for pre-compiled adapter: It would be helpful to take only a part e.g. the `dist` or `asset` folder from the zip file and place it in the target folder.

Often you attach a compiled zip to the Github release with all the files but just need one folder with the assets.

**Comment by Chrico** [comment]
Good morning @goaround 

could you pls show your `asset-compiler.json` or `asset-compiler`-setting in `composer.json` and the Github Action? :) As far is i unterstand you want to create a release zip (when creating a release) and/or build artifact (when pushing into repo) which only contains the `asset`-folder and on the other end you want to unzip this folder again?

**Comment by goaround** [comment]
Good moring @Chrico 

take a look at this release: https://github.com/deworg/dewp-planet-feed/releases/tag/0.5.1 It comes with a `dewp-planet-feed-0.5.1.zip` asset. It contains the whole plugin including the `assets` folder. I just need the `assets` from this zip because I load the rest of the plugin through composer.

With this `asset-compiler.json` it unpacks the whole zip to the /assets dir. 
```json
{
    "script": "production",
    "pre-compiled": {
        "env": {
            "root": {
                "adapter": false
            },
            "$default": {
                "source": "dewp-planet-feed-${version}",
                "target": "./assets/",
		"adapter": "gh-release-zip",
		"config": {
			"repository": "deworg/dewp-planet-feed "
		}
            }
        }
    }
}
```

![grafik](https://user-images.githubusercontent.com/5927337/106721799-70e72c00-6605-11eb-94b7-fa9e28c24639.png)

**Comment by gmazzap** [comment]
@goaround the solution IMO is that in your worflow file you create a zip with just the assets.

So right after this line: https://github.com/deworg/dewp-planet-feed/blob/master/.github/workflows/deploy-workflow.yml#L31

you could add:

```
zip -r dewp-planet-feed-assets.zip dewp-planet-feed/assets/
```
creating _another_ zip for just assets,

and then, at the end of the worflow, you add an additional step:

```yaml
    - name: Upload assets ZIP to release.
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./dewp-planet-feed-assets.zip
        asset_name: dewp-planet-feed-assets.zip
        asset_content_type: application/zip
```

(I'm not sure `actions/upload-release-asset` allow upload multiple assets at once, if so you could combine the two steps uploading zips in one step).

At that point, your configuration you could be:

```json
{
    "script": "production",
    "pre-compiled": {
        "env": {
            "root": {
                "adapter": false
            },
            "$default": {
                "source": "dewp-planet-feed-assets.zip",
                "target": "./assets/",
		"adapter": "gh-release-zip",
		"config": {
		   "repository": "deworg/dewp-planet-feed"
		}
            }
        }
    }
}
```

Addding an additional configuration to target a single folder would require some more compexity due to manage yet another config value, plus dealing with it when unpacking the zip.

Considering that this is something doable already I'm not sure I want to implement that... I'll have to think about it. Opinions? (also @Chrico)

**Comment by goaround** [comment]
Thank you. I now generate an additional assets.zip and this works fine.
